services:
  authapi:
    image: authapi
    build:
      context: .
      dockerfile: AuthAPI/Dockerfile
      
  coffeeapi:
    image: coffeeapi
    build:
      context: .
      dockerfile: CoffeeAPI/Dockerfile
        
  gatewayapi:
    image: gatewayapi
    build:
      context: .
      dockerfile: GatewayAPI/Dockerfile
    ports:
      - 5003:80
